### ISSUE TITLE
Use plugin_ffi template

### ISSUE THREAD

**Issue by dcharkes** [rockingdice/repo_issue_umbrella_header_cpp_integration#1]
Offtopic to the repro: Instead of `flutter create -t plugin` you can now use `flutter create -t plugin_ffi`.

**Comment by rockingdice** [comment]
@dcharkes I found the 'plugin_ffi' is only supported by flutter v3.0, can I use the plugin in an older project like flutter v2.10?

**Comment by dcharkes** [comment]
No, it is not.
